# Generated by Django 3.2.3 on 2021-05-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='descripton',
            field=models.TextField(blank=True, default=''),
        ),
    ]
