# Generated by Django 3.2.3 on 2021-05-28 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_descripton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='descripton',
            new_name='description',
        ),
    ]
